### ISSUE TITLE
缺失cifs的支持

### ISSUE THREAD

**Issue by mayaxcn** [jjm2473/rtd1295-blob#1]
我在使用mount命令挂载远程NAS硬盘的时候，无论是通过SAMBA还是NFS，貌似X9S自带的mount命令都没有支持挂载局域网硬盘的能力，麻烦能确认一下或者更新mount工具吗？萌新一枚~~~

**Comment by jjm2473** [comment]
芝社的这几个设备是Android和Openwrt运行在一个内核里的, 不知道改mount会不会有问题, 我试试.
之前尝试过mount镜像文件, 确实从未成功过.

**Comment by jjm2473** [comment]
试试这两个命令:
挂载SMB:
`mount -t cifs -o username=Everyone,uid=1023,gid=1023 //192.168.1.1/Disk_sda1 /mnt/smb`
挂载NFS:
`mount -t nfs 192.168.1.1:/mnt/sda1 /mnt/nfs`

如果挂载失败, 那么试试我的新项目吧 https://github.com/jjm2473/rtd1295-openwrt18-porting ,更新以后上面两个命令都能挂载成功.
