### ISSUE TITLE
rtd1295的编译SDK是不是下载为Quad-core ARM Cortex A53 (64-bit)类型准备的就行了

### ISSUE THREAD

**Issue by ihipop** [jjm2473/rtd1295-blob#3]
理论上官方源里arm64的类别下的二进制也可以吧？

**Comment by jjm2473** [comment]
如果你是想给zidoo官方的op编译软件，op官方的工具链找不到合适的，主要是libc有点不一样，所以直接用我的这个项目提供的工具链吧：
 https://github.com/jjm2473/rtd1295-toolchain ；
如果是想给我发的op18编译软件，那么下载op官方的snapshot的sunxi的A53工具链就可以了，系统也是从这移植的。

**Comment by ihipop** [comment]
Thanks

**Comment by ihipop** [comment]
你这个toolchain哪来的啊？

**Comment by jjm2473** [comment]
费了点心思从网盘搜到的，不过找到的只是个rtd1295的toolchain，后来跟op的15.0的sdk合并了一下，就成了rtd1295 op 15.0.1的sdk ，哈哈 :)

**Comment by jjm2473** [comment]
实际上也就是a53的toolchain，只是不想自己再编译一个toolchain，就找了个跟zidoo官方的系统匹配的toolchain
