### ISSUE TITLE
可以在你的源里增加 rsync 吗

### ISSUE THREAD

**Issue by materliu** [jjm2473/rtd1295-blob#4]
你好，可以在你的源里增加 rsync 吗

**Comment by jjm2473** [comment]
> 你好，可以在你的源里增加 rsync 吗

编译CC的软件比较麻烦，你看能不能升级到18以上，有官方软件仓库可以用。
https://github.com/jjm2473/rtd1295-openwrt18-porting

**Comment by materliu** [comment]
恩， 我一开始也是尝试升级18的，试了4、5次，都刷不成功。表现就是 openwrt 刷挂掉，重启机器 还是老版本的 openwrt。
才开始用你做的这个源。
